apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: dev
spec:
  limits:
    - type: Pod
      max:
        cpu: 500m
        memory: 1Gi
      min:
        cpu: 50m
        memory: 50Mi
    - type: Container
      default:
        cpu: 150m
        memory: 300Mi
      defaultRequest:
        cpu: 100m
        memory: 250Mi
      maxLimitRequestRatio:
        cpu: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment-failed
  namespace: dev
  labels:
    app: stress-failed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-failed
  template:
    metadata:
      labels:
        app: stress-failed
    spec:
      containers:
      - name: stress-failed
        image: bretfisher/stress:256m
        resources:
          requests:
            cpu: 1000m
          limits: 
            cpu: 1100m

