apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: dev
spec:
  limits:
    - type: Pod
      max:
        cpu: 500m
        memory: 1Gi
      min:
        cpu: 50m
        memory: 50Mi
    - type: Container
      default:
        cpu: 150m
        memory: 300Mi
      defaultRequest:
        cpu: 100m
        memory: 250Mi
      maxLimitRequestRatio:
        cpu: 10

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-and-mem
  namespace: dev
spec:
  hard:
    requests.cpu: 300m
    requests.memory: 2000Mi
    limits.cpu: 350m
    limits.memory: 5000Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
  namespace: dev
  labels:
    app: stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: bretfisher/stress:256m
        resources:
          requests:
            cpu: 100m
          limits: 
            cpu: 200m

