apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    metadata:
      labels:
        app: test-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "sleep 60;" ]
