apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-demo
        image: luksa/init-demo:1.0
      - name: network-check
        image: luksa/network-connectivity-checker:1.0
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
