---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "test"
  APP_PORT: "8080"
  MY_NAME: "hadi"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  MYSQL_RANDOM_ROOT_PASSWORD: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_ROOT_PASSWORD: "YXNkZjEyMzRhc2RmCg=="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-secret
              mountPath: /opt/mysql-secret
              subPath: MYSQL_ROOT_PASSWORD
              readOnly: true
            - name: mysql-config
              mountPath: /opt/mysql-config
              subPath: MYSQL_DATABASE
              readOnly: true
      volumes:
        - name: mysql-secret
          secret:
            secretName: mysql-secret
            items:
              - key: MYSQL_ROOT_PASSWORD
                path: MYSQL_ROOT_PASSWORD

        - name: mysql-config
          configMap:
            name: mysql-config
            items:
              - key: MYSQL_DATABASE
                path: MYSQL_DATABASE

