apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
#    app.kubernetes.io/version: !!str 1.11
    app.kubernetes.io/env: test
spec:
  replicas: 6
  strategy:
    type: Recreate
   # rollingUpdate:
   #   maxSurge: 1
   #   maxUnavailable: 0
  selector: 
    matchLabels:  
      app.kubernetes.io/name: nginx
#      app.kubernetes.io/version: !!str 1.11
      app.kubernetes.io/env: test
  template: 
    metadata:
      labels:      
        app.kubernetes.io/name: nginx
#        app.kubernetes.io/version: !!str 1.11
        app.kubernetes.io/env: test
    spec:
      restartPolicy: Always
      containers:
        - name: nginx
          image: nginx:1.18
          ports:
            - containerPort: 80
