apiVersion: v1
kind: Secret
metadata:
  name: test-sa-token
  annotations:
    kubernetes.io/service-account.name: test-sa
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: default
