apiVersion: v1
kind: Endpoints
metadata:
  name: external-service
subsets:
  - addresses:
      - ip: 10.244.2.6 
    ports:
      - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  ports:
    - port: 80
