apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    #app: nginx
    # Rich labeling
    app.kubernetes.io/name: nginx
    app.kubernetes.io/scope: production
    app.kubernetes.io/part-of: authman
    app.kubernetes.io/created-by: hazdl
    app.kubernetes.io/env: production
    app.kubernetes.io/team: CDN 
  template:
    metadata:
      name: nginx
      labels:
        app: nginx

        app.kubernetes.io/name: nginx
        app.kubernetes.io/scope: production
        app.kubernetes.io/part-of: authman
        app.kubernetes.io/created-by: hazdl
        app.kubernetes.io/env: production
        app.kubernetes.io/team: CDN 
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports: 
            - containerPort: 80        
