apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver
spec:
  replicas: 2
  selector:
    #matchLabels:
    #  app: nginx
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
#          - apache
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80


