# This is just a test. You should use OPA and Gatekeeper and podsecuirtypolicy solutions

apiVersion: v1
kind: Namespace
metadata:
  name: dev
---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: priorityclass-restriction
  namespace: dev
spec:
  hard:
    pods: 0
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values:
          - system-cluster-critical
          - system-node-critical
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-deployment
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      priorityClassName: system-cluster-critical
      containers:
      - name: nginx
        image: nginx:1.14.2-alpine
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
