apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  serviceName: redis-sentinel-service
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
      annotations:
    spec:
      containers:
      - name: redis-sentinel
        command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
        image: redis:latest
        ports:
        - name: redis-sentinel
          containerPort: 26379
        volumeMounts:
        - name: config-map
          mountPath: /etc/redis
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "/usr/local/bin/redis-cli -h $(hostname) -p 26379 ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
      volumes:
      - name: config-map
        configMap:
          name: redis-sentinel-configuration
  volumeClaimTemplates:
  - metadata:
      name: conf
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 200Mi
