apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-service
  namespace: redis
  labels:
    app: redis-sentinel
spec:
  ports:
  - name: redis-sentinel
    port: 26379
  clusterIP: None
  selector:
    app: redis-sentinel